apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadvisor

images:
  - name: cadvisor
    newName: 100.64.176.12:80/cadvisor
    newTag: '3aae36d'

resources:
- serviceaccount.yaml
- daemonset.yaml
- service.yaml
- service_monitor.yaml

configMapGenerator:
  - name: cadvisor-config
    files:
    - perf-hmem-cascadelake.json
