namespace: prometheus

resources:
- prometheusrules.wca-app.yaml
- prometheusrules.wca-app-wss.yaml
- prometheusrules.wca-node-pmem.yaml
- prometheusrules.wca-node.yaml
# - prometheusrules.wca-other.yaml

