nameSuffix: -big
bases:
- ../base

commonLabels:
  app: redis-memtier-big

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - keymaximum_gen=1000000
    - keymaximum_load=1000000
    - extra='--key-stddev=50000'

patchesStrategicMerge:
  - resources.yaml
