# Full example for Kubernetes running as daemonset (in-cluster k8s config)
# Requires environment variables:
# - KUBERNETES_SERVICE_HOST - provided by default by Kuberenetes
# - KUBERNETES_SERVICE_PORT - provided by default by Kubernetes
# - HOST_IP - need to explicitly enabled in Pod spec using downward-api
# - HOSTNAME - default provided by OS
loggers:
  wca.wss: debug

runner: !MeasurementRunner
  interval: 5.0
  node: !KubernetesNode
    cgroup_driver: cgroupfs
    monitored_namespaces: ["default"]
    kubeapi_host: !Env KUBERNETES_SERVICE_HOST
    kubeapi_port: !Env KUBERNETES_SERVICE_PORT
    node_ip: !Env HOST_IP


  metrics_storage: !LogStorage
    overwrite: True
    output_filename: /var/lib/wca/metrics.prom

  extra_labels:
    node: !Env HOSTNAME
  event_names:
    - task_cycles # do not remove: USED BY E2E tests
    - task_instructions
    - task_offcore_requests_demand_data_rd # required fro R/W characterization
    - task_offcore_requests_demand_rfo
    - task_offcore_requests_l3_miss_demand_data_rd__rB010
    - task_offcore_requests_outstanding_l3_miss_demand_data_rd__r6010
  enable_derived_metrics: True
  uncore_event_names:
    - platform_cas_count_reads
    - platform_cas_count_writes
    - platform_pmm_bandwidth_reads
    - platform_pmm_bandwidth_writes

  wss_reset_interval: 60000  # never
  wss_stable_duration: 0 
  # interval is set to 5s
  
  gather_hw_mm_topology: True
