nameSuffix: -small-wss

bases:
- ../base

commonLabels:
  app: redis-memtier-small-wss

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - keymaximum_gen=250000
    - keymaximum_load=250000
    - extra='--key-stddev=250000'

patchesStrategicMerge:
  - resources.yaml
